# This is a basic workflow to help you get started with Actions

name: Stratus Test 2

# Controls when the action will run.
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - name: Run With Error
        if: ${{ github.event.inputs.tags == 'error'}}
        run: |
          echo "Error!" > logfile.log
          sleep 60
          exit 125
        
      - name: Run without error
        if: ${{ github.event.inputs.tags != 'error' }}
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          sleep 60
          echo "Tags: ${{ github.event.inputs.tags }}"
